'use client';
import Link from 'next/link';
import { useState } from 'react';
import { ArrowUpRight, ArrowRight, Sprout, Leaf, Heart, Menu, X, Sun, Users, MapPin, MessageCircle, ChevronDown } from 'lucide-react';
import { Locale, PageKey, copy, href, photos, disclaimer, attribution, resources, titles } from '../content';
import { Action, Closing, ProgramCards, Sphere } from './Shared';
import { ApproachPage, ProgramsPage, StayPage, TeamPage, AftercarePage, LegalPage } from './InformationPages';
import { ResourcePage, ResourceArticle } from './Resources';
import Inquiry from './Inquiry';

export default function Website({locale,page}:{locale:Locale;page:PageKey}) {
  const [menu,setMenu]=useState(false);
  const [chat,setChat]=useState(false);
  const t=(es:string,en:string)=>copy(locale,es,en);
  const nav: [PageKey,string][]=[['approach',t('Nuestro modelo','Our model')],['programs',t('Programas','Programs')],['stay',t('Su estadía','Your stay')],['resources',t('Recursos','Resources')],['team',t('Equipo','Our team')]];
  return <><a className="skip" href="#main">{t('Ir al contenido','Skip to content')}</a><div className="demo-ribbon"><span>{t('VISTA DEMO','DEMO PREVIEW')}</span>{t('Una experiencia de bienestar, arraigada en la fe.','A wellbeing experience, rooted in faith.')}<span className="ribbon-location"><MapPin size={11}/> Bayaguana, {t('República Dominicana','Dominican Republic')}</span></div><header className="header site-header"><Link className="brand" href={href(locale,'home')} aria-label={t('Country Life — inicio','Country Life — home')}><span className="brand-icon"><Sprout size={30} strokeWidth={1.4}/></span><span>Country Life<span className="brand-bottom">LIFESTYLE CENTER</span></span></Link><nav id="main-navigation" className={`navigation ${menu?'expanded':''}`} aria-label={t('Navegación principal','Main navigation')}>{nav.map(([key,label])=><Link key={key} href={href(locale,key)} aria-current={page===key?'page':undefined} onClick={()=>setMenu(false)}>{label}</Link>)}<div className="locale-switch" aria-label={t('Idioma','Language')}><Link href={href('es',page)} lang="es" aria-label="Ver en español" aria-current={locale==='es'?'true':undefined}>ES</Link><span>/</span><Link href={href('en',page)} lang="en" aria-label="View in English" aria-current={locale==='en'?'true':undefined}>EN</Link></div><Link className="button nav-cta" href={href(locale,'inquiry')} onClick={()=>setMenu(false)}>{t('Comience aquí','Start your journey')}<ArrowUpRight size={15}/></Link></nav><button className="menu-toggle" aria-controls="main-navigation" aria-label={menu?t('Cerrar menú','Close menu'):t('Abrir menú','Open menu')} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
  <main id="main">{page==='home'?<Home locale={locale}/>:page==='approach'?<ApproachPage locale={locale}/>:page==='programs'?<ProgramsPage locale={locale}/>:page==='stay'?<StayPage locale={locale}/>:page==='team'?<TeamPage locale={locale}/>:page==='aftercare'?<AftercarePage locale={locale}/>:page==='resources'?<ResourcePage locale={locale}/>:page==='inquiry'?<Inquiry locale={locale}/>:page==='terms'||page==='privacy'?<LegalPage locale={locale} page={page}/>:<ResourceArticle locale={locale} page={page}/>}</main>
  <footer className="footer"><div className="footer-main"><div><Link href={href(locale,'home')} className="brand"><span className="brand-icon"><Sprout size={29} strokeWidth={1.4}/></span><span>Country Life<span className="brand-bottom">LIFESTYLE CENTER</span></span></Link><p>{t('Una nueva forma de vivir.','A new way of living.')}<br/>{t('Cuerpo. Mente. Espíritu.','Body. Mind. Spirit.')}</p><span className="footer-place"><MapPin size={13}/>Bayaguana, República Dominicana</span></div><div className="footer-links"><span>{t('DESCUBRA','EXPLORE')}</span>{nav.slice(0,3).map(([key,label])=><Link href={href(locale,key)} key={key}>{label}</Link>)}<Link href={href(locale,'team')}>{t('Nuestro equipo','Our team')}</Link></div><div className="footer-links"><span>{t('SIGA CRECIENDO','KEEP GROWING')}</span><Link href={href(locale,'resources')}>{t('Biblioteca de recursos','Resource library')}</Link><Link href={href(locale,'aftercare')}>{t('Coaching y acompañamiento','Aftercare & coaching')}</Link><Link href={`${href(locale,'inquiry')}?interest=group`}>{t('Experiencias para grupos','Group experiences')}</Link><Link href={href(locale,'inquiry')}>{t('Hablemos','Get in touch')} ↗</Link></div><div className="footer-belief"><Sprout size={26} strokeWidth={1.3}/><p>{t('Arraigados en la fe.','Rooted in faith.')}<br/>{t('Creciendo en bienestar.','Growing in wellbeing.')}</p></div></div><div className="disclaimer"><strong>{t('Un instituto educativo. Una experiencia integral.','An educational institute. A whole-person experience.')}</strong><p>{disclaimer[locale]}</p><p>{attribution[locale]}</p><p className="small-note">{t('Demostración de frontend. Las fotografías son ilustrativas; no representan las instalaciones reales. No se envían consultas ni se procesan pagos.','Frontend demonstration. Photography is illustrative and does not represent the actual facilities. No enquiries are sent and no payments are processed.')}</p></div><div className="footer-bottom"><span>© 2026 Country Life Institute Dominican Republic.</span><div><Link href={href(locale,'terms')}>{t('Términos','Terms')}</Link><Link href={href(locale,'privacy')}>{t('Privacidad','Privacy')}</Link><a href="#main">{t('Volver arriba','Back to top')} ↑</a></div></div></footer>
  {chat&&<aside className="chat-panel" aria-labelledby="chat-title"><button className="chat-close" onClick={()=>setChat(false)} aria-label={t('Cerrar contacto','Close contact')}><X size={18}/></button><span className="eyebrow">{t('CONVERSEMOS','LET’S CONNECT')}</span><h3 id="chat-title">Sarah Bohórquez</h3><p>{t('Su guía para el próximo paso. En el sitio final podrá conversar por WhatsApp con nuestra coordinadora.','Your guide to the next step. On the final site you will be able to chat with our coordinator on WhatsApp.')}</p><div className="demo-note">{t('Demo: número de WhatsApp pendiente de configuración.','Demo: WhatsApp number awaiting configuration.')}</div><Link className="button" href={href(locale,'inquiry')} onClick={()=>setChat(false)}>{t('Ver consulta inicial','View initial enquiry')}<ArrowRight size={15}/></Link></aside>}
  <button className="whatsapp-button" aria-label={t('Contacto por WhatsApp — demo','WhatsApp contact — demo')} aria-expanded={chat} onClick={()=>setChat(!chat)}>{chat?<X size={23}/>:<MessageCircle size={24}/>}</button></>;
}

function Home({locale}:{locale:Locale}) {
  const t=(es:string,en:string)=>copy(locale,es,en);
  const i=locale==='es'?0:1;
  return <><section className="hero country-hero"><img className="hero-img" src={photos.hero} alt={t('Luz del sol entre los árboles de un bosque verde','Sunlight through the trees of a green forest')} fetchPriority="high"/><div className="hero-shade"/><div className="hero-content"><span className="eyebrow light"><span className="tiny-dot"/>{t('UN RESPIRO. UN NUEVO COMIENZO.','A LITTLE SPACE. A NEW BEGINNING.')}</span><h1>{t('Una pausa para','A little space to')}<br/>{t('volver a','come back to')}<br/><em>{t('sentirse pleno.','feeling whole.')}</em></h1><p>{t('Un ritmo más tranquilo. Hábitos con propósito.','A quieter pace. Habits with purpose.')}<br/>{t('Una experiencia de vida que nutre su cuerpo,','A living experience that nurtures your body,')}<br/>{t('su mente y su espíritu.','your mind, and your spirit.')}</p><Action locale={locale} page="programs" orange>{t('Encuentre su programa','Find your program')}</Action></div><div className="hero-stamp"><Sprout size={28}/><span>{t('CUERPO · MENTE · ESPÍRITU','BODY · MIND · SPIRIT')}</span><small>{t('El arte de vivir bien.','The art of living well.')}</small></div><div className="hero-bottom"><span>{t('ARRAIGADOS EN LA FE. INSPIRADOS POR LA NATURALEZA.','ROOTED IN FAITH. INSPIRED BY NATURE.')}</span><a href="#welcome">{t('Descubra otra forma de vivir','Discover a different way of living')}<span className="circle-arrow">↓</span></a></div></section><div className="values-strip"><span><Leaf/>{t('Educación bíblica integral','Bible-based lifestyle education')}</span><span><Users/>{t('Hasta 14 huéspedes','Up to 14 guests')}</span><span><Sun/>{t('Estadías de 7, 14 y 21 días','7, 14 & 21-day stays')}</span><span><Heart/>{t('Apoyo más allá de su estadía','Support beyond your stay')}</span></div>
  <section id="welcome" className="section approach"><div className="approach-photo"><img src={photos.forest} alt={t('Un rincón del bosque para hacer una pausa','A quiet corner of the forest to pause')} loading="lazy"/><div className="photo-note"><Sprout size={25}/><span>{t('Menos prisa.','Less rush.')}<br/><em>{t('Más vida.','More living.')}</em></span></div><span className="image-caption">BAYAGUANA · REPÚBLICA DOMINICANA</span></div><div className="approach-copy"><span className="eyebrow">{t('BIENVENIDO A COUNTRY LIFE','WELCOME TO COUNTRY LIFE')}</span><h2>{t('Un cambio de entorno.','A change of scenery.')}<br/><em>{t('Un cambio interior.','A change from within.')}</em></h2><p>{t('A veces, avanzar comienza por hacer una pausa. Alejarse del ruido, dejar la rutina y encontrar espacio para lo que realmente importa.','Sometimes, moving forward starts with stepping away. From the noise, from the routine, and toward what really matters.')}</p><p>{t('Somos un instituto educativo y un espacio de vida restauradora. A través de principios bíblicos, experiencias prácticas y una comunidad cercana, le acompañamos a construir su propia esfera de bienestar personal.','We are an educational institute and a sanctuary for restorative living. Through biblical principles, practical experiences, and a caring community, we help you build your own personal wellness sphere.')}</p><Link className="text-link" href={href(locale,'approach')}>{t('Conozca nuestra filosofía','Get to know our philosophy')}<ArrowUpRight size={18}/></Link></div></section>
  <section className="section home-sphere"><div className="section-heading"><span className="eyebrow">{t('EL MODELO ESFERA DE BIENESTAR 3×3™','THE 3×3 WELLNESS SPHERE MODEL™')}</span><h2>{t('Todo conectado.','All connected.')} <em>{t('Todo usted.','All of you.')}</em></h2><p>{t('Tres pilares. Nueve principios. Una forma integral de vivir.','Three pillars. Nine principles. One whole-person way of living.')}</p></div><Sphere locale={locale}/></section>
  <section className="program-section section"><div className="split-heading"><div><span className="eyebrow">{t('HAGA TIEMPO PARA USTED','MAKE TIME FOR YOURSELF')}</span><h2>{t('Su ritmo.','Your pace.')}<br/><em>{t('Su nuevo comienzo.','Your new beginning.')}</em></h2></div><p>{t('Elija el tiempo para aprender, practicar y reconectar. Cada programa combina alojamiento, alimentación integral y experiencias educativas en comunidad.','Choose your time to learn, practice, and reconnect. Each program brings together accommodation, whole-food meals, and educational experiences in community.')}</p></div><ProgramCards locale={locale}/></section>
  <section className="section stay-section"><div className="stay-copy"><span className="eyebrow">{t('LLEGUE. RESPIRE. SIÉNTASE EN CASA.','SETTLE IN. BREATHE. FEEL AT HOME.')}</span><h2>{t('Un lugar para descansar.','A place to rest.')}<br/><em>{t('Un espacio para crecer.','A space to grow.')}</em></h2><p>{t('Comodidades sencillas, momentos compartidos y el verdor de Bayaguana. Desde La Mesa Viva hasta las caminatas diarias, cada día es una oportunidad de aprendizaje.','Simple comforts, shared moments, and the greenery of Bayaguana. From The Living Table to daily walks, every day is an opportunity to learn.')}</p><Link href={href(locale,'stay')} className="text-link">{t('Imagine su estadía','Picture your stay')}<ArrowUpRight size={17}/></Link></div><div className="stay-collage"><img className="room-photo" src={photos.room} alt={t('Habitación de referencia para una estadía tranquila','Illustrative room for a restful stay')} loading="lazy"/><img className="food-photo" src={photos.food} alt={t('Ingredientes vegetales coloridos','Colorful plant-based ingredients')} loading="lazy"/><span className="collage-label">{t('Buena mesa. Buena compañía.','Good food. Good company.')}<br/><em>{t('Alegría en lo cotidiano.','Joy in the everyday.')}</em></span></div></section>
  <section className="aftercare"><div className="aftercare-art" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="orbit orbit-three"/><Sprout size={116} strokeWidth={.8}/><span>{t('SEGUIR CRECIENDO, CADA DÍA','KEEP GROWING, EVERY DAY')}</span></div><div className="aftercare-copy"><span className="eyebrow">{t('LLEVE EL CAMBIO A CASA','TAKE THE CHANGE HOME')}</span><h2>{t('Su estadía termina.','Your stay ends.')}<br/><em>{t('Su camino continúa.','Your journey continues.')}</em></h2><p>{t('Los nuevos hábitos crecen con apoyo. Nuestro programa opcional de acompañamiento le ayuda a integrar lo aprendido en la vida cotidiana, un paso a la vez.','New habits grow with support. Our optional aftercare program helps you bring what you have learned into everyday life, one step at a time.')}</p><Link className="text-link" href={href(locale,'aftercare')}>{t('Descubra el acompañamiento','Discover aftercare coaching')}<ArrowUpRight size={17}/></Link></div></section>
  <section className="section"><div className="split-heading resource-heading"><div><span className="eyebrow">{t('IDEAS PARA UNA VIDA MÁS PLENA','IDEAS FOR A FULLER LIFE')}</span><h2>{t('Pequeños pasos.','Small steps.')} <em>{t('Nuevas posibilidades.','New possibilities.')}</em></h2></div><Link className="text-link" href={href(locale,'resources')}>{t('Ver biblioteca','Visit the library')}<ArrowUpRight size={17}/></Link></div><div className="resource-grid">{resources.slice(0,3).map(r=><Link href={href(locale,r.id)} className="resource-card" key={r.id}><div className="resource-image"><img src={r.image} alt={titles[r.id][i]} loading="lazy"/><span>{r.type==='recipe'?t('LA MESA VIVA','THE LIVING TABLE'):t('ESTILO DE VIDA','LIFESTYLE')}</span></div><div className="resource-card-body"><span className="micro">{r.minutes} MIN · {t('LECTURA PARA CRECER','A LITTLE ROOM TO GROW')}</span><h3>{titles[r.id][i]}</h3><p>{r.excerpt[i]}</p><ArrowUpRight size={19}/></div></Link>)}</div></section><FAQ locale={locale}/><Closing locale={locale}/></>;
}

export function FAQ({locale}:{locale:Locale}) {
  const t=(es:string,en:string)=>copy(locale,es,en);
  const [open,setOpen]=useState<number|null>(0);
  const questions=[
    [t('¿Qué tipo de institución es Country Life?','What kind of institution is Country Life?'),t('Somos un instituto educativo dedicado a la restauración del estilo de vida. Nuestros programas complementan la atención de su médico personal; no la sustituyen.','We are an educational institute dedicated to lifestyle restoration. Our programs complement the care of your personal physician; they do not replace it.')],
    [t('¿Qué incluye el costo del programa?','What does the program tuition include?'),t('La tarifa de $60 USD por día incluye alojamiento en habitación doble, comidas 100% a base de plantas, sesiones prácticas, coaching y materiales educativos. El transporte, el acompañante y las mejoras de habitación se cotizan aparte.','The $60 USD daily tuition includes double-occupancy lodging, 100% plant-based meals, practical sessions, coaching, and educational materials. Transport, a personal assistant, and room upgrades are additional.')],
    [t('¿Cómo se confirma una reservación?','How is a reservation confirmed?'),t('Primero se completa una consulta inicial y una conversación de orientación. Después de la revisión y aceptación por el equipo, se solicita un depósito de $420 USD, aplicado al costo del programa. Esta demo no realiza reservaciones ni cobra pagos.','First, complete an initial enquiry and an orientation conversation. Following staff review and acceptance, a $420 USD deposit is requested and applied toward program tuition. This demo does not make reservations or collect payments.')],
    [t('¿Puedo venir con un asistente personal?','Can I bring a personal assistant?'),t('Sí. Los huéspedes ambulatorios que necesitan apoyo pueden venir con un acompañante dedicado por $20 USD al día, con alojamiento y comidas incluidos.','Yes. Ambulatory guests who need support can bring a dedicated personal assistant for $20 USD per day, including accommodation and meals.')],
    [t('¿Hay apoyo después de mi estadía?','Is there support after my stay?'),t('Sí. El programa opcional de acompañamiento ofrece coaching, seguimiento y orientación para cultivar sus hábitos en casa. La frecuencia y los detalles se acuerdan con el equipo.','Yes. Optional aftercare offers coaching, check-ins, and guidance to cultivate your habits at home. Frequency and details are arranged with the team.')],
    [t('¿Ofrecen experiencias para grupos?','Do you offer group experiences?'),t('Estamos planificando programas especiales para comunidades y grupos. Indique su interés en la consulta para conversar sobre objetivos, fechas y disponibilidad.','Specialty programs for communities and groups are being planned. Share your interest through the enquiry to discuss goals, dates, and availability.')],
  ];
  return <section className="faq-section section"><div><span className="eyebrow">{t('UN POCO MÁS DE CLARIDAD','A LITTLE MORE CLARITY')}</span><h2>{t('Antes de','Before you')}<br/><em>{t('comenzar.','begin.')}</em></h2><p>{t('Las buenas preguntas son parte de todo nuevo camino.','Good questions are part of every new journey.')}</p><Link className="text-link" href={href(locale,'inquiry')}>{t('¿Tiene otra pregunta?','Have another question?')}<ArrowUpRight size={17}/></Link></div><div className="faq-list">{questions.map(([q,a],n)=><div className="faq-item" key={q}><h3><button onClick={()=>setOpen(open===n?null:n)} aria-expanded={open===n} aria-controls={`answer-${n}`}>{q}<ChevronDown className={open===n?'rotate':''} size={18}/></button></h3><div id={`answer-${n}`} hidden={open!==n}><p>{a}</p></div></div>)}</div></section>;
}
